import { ThemeProvider } from '@/components/ui/theme-provider'
import Authprovider from '@/providers/auth'
import { Theme } from '@radix-ui/themes'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Authprovider>
          <Theme>
            <ThemeProvider attribute="class" defaultTheme="system">
              {children}
            </ThemeProvider>
          </Theme>
        </Authprovider>
      </body>
    </html>
  )
}
