const Config = () => {
  return (
    <div className="ml-5">
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
    </div>
  )
}

export default Config
