const Config = () => {
  return (
    <div>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
      <h1>config page</h1>
    </div>
  )
}

export default Config
